export enum ActionType {
    INSERT_CELL_AFTER = "INSERT_CELL_AFTER",
    UPDATE_CELL = "UPDATE_CELL",
    BUNDLE_START = "BUNDLE_START",
    BUDEDLE_COMPLETE = "BUDEDLE_COMPLETE",
    MOVE_CELL = "MOVE_CELL",
    DELETE_CELL = "DELETE_CELL"
}